
export interface Product {
    id: string;
    name: string;
    price: number;
    category: string;
    image: string;
    description: string;
    features: string[];
    materials: string[];
    allergyTags: string[];
    inStock: boolean;
}

export const products: Product[] = [
    {
        id: "1",
        name: "Housse Intégrale Matelas",
        price: 89.000,
        category: "Literie",
        image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?q=80&w=1000&auto=format&fit=crop",
        description: "Barrière absolue contre 99.9% des acariens et poussières. Tissu micro-tissé silencieux pour des nuits paisibles.",
        features: ["Micro-tissage", "Respirant", "Fermeture sécurisée"],
        materials: ["Evolon® 100", "Microfibres"],
        allergyTags: ["Sans Acariens", "Asthme"],
        inStock: true,
    },
    {
        id: "2",
        name: "Ensemble Pyjama Coton Bio",
        price: 120.000,
        category: "Vêtements",
        image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=1000&auto=format&fit=crop",
        description: "Douceur extrême sans traitement chimique. Idéal pour l'eczéma et les peaux atopiques.",
        features: ["Coutures plates", "Non-teint", "Thermorégulateur"],
        materials: ["100% Coton GOTS"],
        allergyTags: ["Eczéma", "Peau Sensible", "Sans Latex"],
        inStock: true,
    },
    {
        id: "3",
        name: "Lessive Liquide Pure (3L)",
        price: 45.000,
        category: "Maison",
        image: "https://images.unsplash.com/photo-1610484826967-09c5720778c7?q=80&w=1000&auto=format&fit=crop",
        description: "Nettoie en profondeur sans irriter. Formule biodégradable sans parfums ni azurants optiques.",
        features: ["Hypoallergénique", "Concentrée", "Mousse contrôlée"],
        materials: ["Savon végétal", "Citrate de sodium"],
        allergyTags: ["Sans Parfum", "Sans Conservateurs"],
        inStock: true,
    },
    {
        id: "4",
        name: "Ceinture Cuir Sans Nickel",
        price: 35.000,
        category: "Accessoires",
        image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1000&auto=format&fit=crop",
        description: "Le style sans les démangeaisons. Boucle en titane certifiée 100% sans nickel.",
        features: ["Cuir pleine fleur", "Boucle Titane", "Durable"],
        materials: ["Cuir Italien", "Titane"],
        allergyTags: ["Sans Nickel", "Dermatite"],
        inStock: true,
    },
    {
        id: "5",
        name: "Savon Sfaxien Traditionnel",
        price: 8.500,
        category: "Soins",
        image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?q=80&w=1000&auto=format&fit=crop",
        description: "L'or vert de la Tunisie. Saponifié à froid, riche en glycérine naturelle protectrice.",
        features: ["Surgras", "Sans huile de palme", "Vegan"],
        materials: ["Huile d'Olive Vierge"],
        allergyTags: ["Sans Parfum", "Naturel"],
        inStock: true,
    },
    {
        id: "6",
        name: "Chaussettes Bambou Respirantes",
        price: 28.000,
        category: "Vêtements",
        image: "https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?q=80&w=1000&auto=format&fit=crop",
        description: "Vos pieds vous remercieront. Fibre de bambou ultra-douce et naturellement antibactérienne.",
        features: ["Anti-odeurs", "Pointe sans couture", "Extensible"],
        materials: ["80% Bambou", "18% Polyamide", "2% Élasthanne"],
        allergyTags: ["Peau Sensible", "Douceur"],
        inStock: true,
    },
    {
        id: "7",
        name: "Oreiller Ergonomique Anti-Acarien",
        price: 55.000,
        category: "Literie",
        image: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e6?q=80&w=1000&auto=format&fit=crop",
        description: "Soutien cervical parfait avec traitement naturel anti-acarien à l'huile de neem.",
        features: ["Anatomique", "Housse lavable", "Ferme"],
        materials: ["Mousse Mémoire", "Housse Bambou"],
        allergyTags: ["Sans Acariens", "Peau Sensible"],
        inStock: true,
    },
    {
        id: "8",
        name: "Crème Hydratante Avoine",
        price: 32.000,
        category: "Soins",
        image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=1000&auto=format&fit=crop",
        description: "Apaisement immédiat pour peaux irritées. Formule riche à l'avoine colloïdale.",
        features: ["Apaisant", "Sans parfum", "24h Hydratation"],
        materials: ["Avoine", "Beurre de Karité"],
        allergyTags: ["Peau Sensible", "Eczéma", "Sans Parfum"],
        inStock: true,
    },
    {
        id: "9",
        name: "T-Shirt Chanvre Naturel",
        price: 45.000,
        category: "Vêtements",
        image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=1000&auto=format&fit=crop",
        description: "Le tissu le plus écologique. Résistant, respirant et devient plus doux à chaque lavage.",
        features: ["Thermorégulateur", "Antibactérien", "Durable"],
        materials: ["100% Chanvre"],
        allergyTags: ["Peau Sensible", "Sans Conservateurs"],
        inStock: true,
    },
    {
        id: "10",
        name: "Masque Visage Argile Verte",
        price: 18.500,
        category: "Soins",
        image: "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?q=80&w=1000&auto=format&fit=crop",
        description: "Purifie sans dessécher. Argile verte séchée au soleil tunisien.",
        features: ["Purifiant", "100% Naturel", "Detox"],
        materials: ["Argile Verte Montmorillonite"],
        allergyTags: ["Sans Parfum", "Sans Conservateurs"],
        inStock: true,
    },
    {
        id: "11",
        name: "Gants Nitrile Non-Poudrés",
        price: 15.000,
        category: "Accessoires",
        image: "https://images.unsplash.com/photo-1584634731339-252c581abfc5?q=80&w=1000&auto=format&fit=crop",
        description: "Protection des mains sans risque d'allergie au latex. Idéal pour le ménage ou les soins.",
        features: ["Resistant", "Sensibilité tactile", "Boîte de 100"],
        materials: ["Nitrile"],
        allergyTags: ["Sans Latex", "Peau Sensible"],
        inStock: true,
    },
    {
        id: "12",
        name: "Bougies Cire d'Abeille Pure",
        price: 26.000,
        category: "Maison",
        image: "https://images.unsplash.com/photo-1603006905003-be475563bc59?q=80&w=1000&auto=format&fit=crop",
        description: "Purifiez l'air naturellement. Brûle proprement sans fumée toxique ni paraffine.",
        features: ["Longue durée", "Odeur miellée", "Ionisant"],
        materials: ["Cire d'Abeille"],
        allergyTags: ["Sans Parfum", "Peau Sensible"],
        inStock: true,
    },
    {
        id: "13",
        name: "Drap Housse Percale Bio",
        price: 75.000,
        category: "Literie",
        image: "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?q=80&w=1000&auto=format&fit=crop",
        description: "Percale de coton bio 80 fils/cm². Frais et craquant, s'adoucit avec le temps.",
        features: ["Grand bonnet", "GOTS", "Repassage facile"],
        materials: ["Coton Bio"],
        allergyTags: ["Peau Sensible", "Eczéma"],
        inStock: true
    },
    {
        id: "14",
        name: "Nettoyant Sol Écologique (5L)",
        price: 38.000,
        category: "Maison",
        image: "https://images.unsplash.com/photo-1563453392212-326f5e854473?q=80&w=1000&auto=format&fit=crop",
        description: "Pour toutes surfaces lavables. Sans COV, sans parfums de synthèse. Sécurité bébé.",
        features: ["Economique", "PH Neutre", "Brillance naturelle"],
        materials: ["Savon Noir", "Huiles Essentielles"],
        allergyTags: ["Sans Parfum", "Sans Conservateurs"],
        inStock: true
    },
    {
        id: "15",
        name: "Brosse à Dents Bambou (x4)",
        price: 22.000,
        category: "Soins",
        image: "https://images.unsplash.com/photo-1607613009820-a29f7bb6dc2d?q=80&w=1000&auto=format&fit=crop",
        description: "Alternative zéro déchet. Manche biodégradable et poils souples infusés au charbon.",
        features: ["Poils souples", "Antibactérien", "Compostable"],
        materials: ["Bambou Moso", "Nylon-6"],
        allergyTags: ["Sans Latex", "Peau Sensible"],
        inStock: true
    },
    {
        id: "16",
        name: "Collier Ambre Bébé",
        price: 45.000,
        category: "Accessoires",
        image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=1000&auto=format&fit=crop",
        description: "Ambre de la Baltique certifié. Fermoir sécurité pop-up sans métal.",
        features: ["Sécurisé", "Pierre Naturelle", "Apaisant"],
        materials: ["Ambre", "Fil de soie"],
        allergyTags: ["Sans Nickel", "Peau Sensible"],
        inStock: true
    },
    {
        id: "17",
        name: "Écharpe Lin Lavé",
        price: 55.000,
        category: "Vêtements",
        image: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?q=80&w=1000&auto=format&fit=crop",
        description: "Légère et aérienne pour la mi-saison. Ne gratte absoluement pas.",
        features: ["Thermorégulateur", "Style Bohème", "Tintures végétales"],
        materials: ["100% Lin Européen"],
        allergyTags: ["Sans Laine", "Peau Sensible"],
        inStock: true
    },
    {
        id: "18",
        name: "Spray Assainissant Air",
        price: 29.000,
        category: "Maison",
        image: "https://images.unsplash.com/photo-1628088062854-d1870b4553da?q=80&w=1000&auto=format&fit=crop",
        description: "Aux 41 huiles essentielles. Élimine virus, bactéries et mauvaises odeurs naturellement.",
        features: ["Aérosol sans gaz", "Efficacité prouvée", "Bio"],
        materials: ["Huiles Essentielles"],
        allergyTags: ["Sans Parfum", "Sans Conservateurs"],
        inStock: true
    },
    {
        id: "19",
        name: "Shampoing Solide Doux",
        price: 19.500,
        category: "Soins",
        image: "https://images.unsplash.com/photo-1608248597279-f99d160bfbc8?q=80&w=1000&auto=format&fit=crop",
        description: "Base lavante ultra-douce au lait d'avoine. Mousse onctueuse sans sulfates.",
        features: ["Zéro Déchet", "Démêlant", "PH physioloqique"],
        materials: ["SCI", "Poudre d'Avoine"],
        allergyTags: ["Sans Perfume", "Sans Conservateurs", "Eczéma"],
        inStock: true
    },
    {
        id: "20",
        name: "Montre Bois Hypoallergénique",
        price: 180.000,
        category: "Accessoires",
        image: "https://images.unsplash.com/photo-1619142835266-281b37805177?q=80&w=1000&auto=format&fit=crop",
        description: "Boîtier et bracelet en bois de santal. Le fond de boîtier est en bois pour éviter tout contact métal.",
        features: ["Mouvement Quartz", "Ultra léger", "Design unique"],
        materials: ["Bois de Santal", "Verre Minéral"],
        allergyTags: ["Sans Nickel", "Peau Sensible"],
        inStock: true
    },
    {
        id: "21",
        name: "Couverture Pondérée Coton",
        price: 145.000,
        category: "Literie",
        image: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?q=80&w=1000&auto=format&fit=crop",
        description: "Réduit l'anxiété et améliore le sommeil. 100% coton bio respirant.",
        features: ["Poids réparti", "Anti-stress", "Housse amovible"],
        materials: ["Coton GOTS", "Billes de verre"],
        allergyTags: ["Peau Sensible", "Sans Latex"],
        inStock: true
    },
    {
        id: "22",
        name: "Bandeau Cheveux Soie Pure",
        price: 39.000,
        category: "Accessoires",
        image: "https://images.unsplash.com/photo-1576016773942-3344d363ef59?q=80&w=200",
        description: "Protège vos cheveux et votre front. Soie de mûrier 22 momme.",
        features: ["Anti-frisottis", "Doux", "Hypoallergénique"],
        materials: ["100% Soie"],
        allergyTags: ["Peau Sensible", "Eczéma"],
        inStock: true
    },
    {
        id: "23",
        name: "Kit Voyage Soins Bio",
        price: 48.000,
        category: "Soins",
        image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d52d?q=80&w=1000&auto=format&fit=crop",
        description: "Vos essentiels en format cabine. Shampoing, Douche et Lait corps sans sulfates.",
        features: ["Format 100ml", "Certifié Bio", "Flacons rechargeables"],
        materials: ["Ingrédients naturels"],
        allergyTags: ["Sans Parfum", "Sans Conservateurs"],
        inStock: true
    },
    {
        id: "24",
        name: "Torchon Cuisine Chanvre",
        price: 19.500,
        category: "Maison",
        image: "https://images.unsplash.com/photo-1590736704728-f4730bb3c3af?q=80&w=1000&auto=format&fit=crop",
        description: "Absorption supérieure et naturellement antifongique. Séchage rapide.",
        features: ["Durable", "Antibactérien", "Zéro Déchet"],
        materials: ["55% Chanvre", "45% Coton"],
        allergyTags: ["Peau Sensible"],
        inStock: true
    }
];

export const categories = [
    "Tout",
    "Literie",
    "Vêtements",
    "Maison",
    "Accessoires",
    "Soins"
];

export const allergyFilters = [
    "Sans Acariens",
    "Sans Laine",
    "Sans Latex",
    "Sans Nickel",
    "Sans Parfum",
    "Sans Conservateurs",
    "Eczéma",
    "Peau Sensible"
];
